package de.swt.scenedirector;

public enum RequiredAction {
	NONE,
	LAGER_SHOW_LAGERPLATZ,
	PRODUKT_SHOW_PRODUKT,
	RECHNUNG_SHOW_RECHNUNG,
	LAGER_SHOW_LAGER,
	LAGER_NEW_LAGERPLATZ,
	PRODUKT_NEED_SELECTED_PRODUKT,
	LAGERPLATZ_PRODUKT_AMOUNT
}
